"""Build labeled scan-photo fixtures for the iOS accuracy harness (Plan 2 Phase G).

Produces, under ios/TheTin/Tests/Fixtures/ScanPhotos/:
  - labels.json          64 photos -> {plate, truthIds:[...], condition}
  - labeled-pack.sqlite  nf=650 fingerprint reference pack (unique truth ids + distractors)
  - labeled-catalog.sqlite  Plan-1 catalog subset (set_info+printed_total, card, card_text
    FTS5 with real attack/ability text, card_twin) for the same ids

Canonical PLATES (the doc-seg-detected 660x920 crops, IMG_<num>.pngdata) are NOT built here.
They're generated by fingerprint/eval/make_scan_plates.swift, which runs the same
detect+orient algorithm as the production CardDetector (Phase D) — this script's old
Canny quad()/warp() plate path is retired: Canny plates don't reproduce the proven doc-seg
accuracy numbers.

Run from fingerprint/. Needs a local gunzipped catalog-v3.sqlite (see CAT below) and network
access to api.tcgdex.net for card text / printed_total (one-time fixture build, not part of
the app or of CI).
"""
import gzip, json, os, random, shutil, sqlite3, urllib.request, time
from fpcore import descriptors as fpdesc, canonicalize, codebook as cbmod, packing, fpdb
import cv2

OUT = "../ios/TheTin/Tests/Fixtures/ScanPhotos"
CACHE = ".cache/images"
CATALOG_GZ = "../functions/.seed-output/catalog/catalog-v3.sqlite.gz"
CATALOG_LOCAL = "/tmp/catalog-v3-g1.sqlite"
TRUTH_TXT = "eval/truth.txt"
IMAGES_CSV = "../test_images/images.csv"
N_DISTRACTORS = 50
TCGDEX = "https://api.tcgdex.net/v2/en"

# Photos whose ground truth isn't a single confident row in truth.txt (resolve_truth.py
# flagged them AMBIG/NONE — see fingerprint/eval/README.md and scorer.py's AMBIG dict).
# 1542/1543: "Articuno" (CSV label omits "ex") name-matched 3 wrong candidates; the actual
# card is np-32 "Articuno ex" (HP 100, #032/40) — confirmed by direct catalog lookup, not
# resolve_truth's exact-name match. 1547/1552: genuine identical-art twin pools (Plan 1
# card_twin candidates) where any member is an acceptable lock.
SPECIAL_TRUTH = {
    "1542": ["np-32"], "1543": ["np-32"],
    "1547": ["base1-2", "base4-2", "dp3-2", "pl1-2"],
    "1552": ["ex1-14", "ex12-14"],
}
TWIN_PAIRS = [("base1-2", "base4-2"), ("base1-2", "dp3-2"), ("base1-2", "pl1-2"),
              ("base4-2", "dp3-2"), ("base4-2", "pl1-2"), ("dp3-2", "pl1-2"),
              ("ex1-14", "ex12-14")]


def load_truth_map():
    truth = {}
    for line in open(TRUTH_TXT):
        num, cid = line.split()
        truth[num] = [cid]
    truth.update(SPECIAL_TRUTH)
    return truth


def load_conditions():
    cond = {}
    with open(IMAGES_CSV) as f:
        next(f)
        for line in f:
            parts = [p.strip() for p in line.strip().split(",")]
            if not parts or not parts[0]:
                continue
            cond[parts[0]] = parts[-1]
    return cond


def build_labels():
    truth = load_truth_map()
    cond = load_conditions()
    labels = []
    for num in sorted(cond, key=int):
        if num not in truth:
            continue
        labels.append({"plate": f"IMG_{num}", "truthIds": truth[num], "condition": cond[num]})
    assert len(labels) == 64, f"expected 64 labeled photos, got {len(labels)}"
    return labels


def fetch_json(url, retries=3):
    for attempt in range(retries):
        try:
            with urllib.request.urlopen(url, timeout=10) as r:
                return json.load(r)
        except Exception:
            if attempt == retries - 1:
                raise
            time.sleep(1)


def card_text_body(card_id):
    """Mirrors functions/src/upstream/tcgdex.ts buildCardText: ability/attack name+effect,
    joined by newline. Real text for the shipped Plan-1 card_text.body field."""
    doc = fetch_json(f"{TCGDEX}/cards/{card_id}")
    parts = []
    for a in doc.get("abilities") or []:
        if a.get("name"):
            parts.append(a["name"])
        if a.get("effect"):
            parts.append(a["effect"])
    for a in doc.get("attacks") or []:
        if a.get("name"):
            parts.append(a["name"])
        if a.get("effect"):
            parts.append(a["effect"])
    return "\n".join(parts)


def set_printed_total(set_id, _cache={}):
    if set_id in _cache:
        return _cache[set_id]
    doc = fetch_json(f"{TCGDEX}/sets/{set_id}")
    official = doc.get("cardCount", {}).get("official")
    _cache[set_id] = official
    return official


def ensure_local_catalog():
    if not os.path.exists(CATALOG_LOCAL):
        with gzip.open(CATALOG_GZ, "rb") as src, open(CATALOG_LOCAL, "wb") as dst:
            shutil.copyfileobj(src, dst)
    return sqlite3.connect(CATALOG_LOCAL)


LABELED_CATALOG_SCHEMA = """
CREATE TABLE set_info(id TEXT PRIMARY KEY, name TEXT NOT NULL, release_date TEXT,
  total INTEGER NOT NULL, printed_total INTEGER, era TEXT, rep_card_id TEXT);
CREATE TABLE card(id TEXT PRIMARY KEY, set_id TEXT NOT NULL REFERENCES set_info(id),
  number TEXT NOT NULL, name TEXT NOT NULL, hp INTEGER, types TEXT, rarity TEXT, artist TEXT,
  image_base TEXT, image_url TEXT, tcgplayer_id INTEGER);
CREATE VIRTUAL TABLE card_text USING fts5(card_id UNINDEXED, name, body);
CREATE TABLE card_twin(card_id TEXT NOT NULL, twin_id TEXT NOT NULL, PRIMARY KEY(card_id, twin_id));
"""


def build_catalog_fixture(card_ids):
    con = ensure_local_catalog()
    rows = {}
    for cid in card_ids:
        r = con.execute(
            "SELECT c.id,c.set_id,c.number,c.name,c.hp,s.name,s.release_date,s.total,s.era "
            "FROM card c JOIN set_info s ON s.id=c.set_id WHERE c.id=?", (cid,)).fetchone()
        assert r is not None, f"card {cid} missing from local catalog-v3.sqlite"
        rows[cid] = r
    sets = {}
    for r in rows.values():
        set_id = r[1]
        if set_id not in sets:
            sets[set_id] = {"id": set_id, "name": r[5], "release_date": r[6], "total": r[7], "era": r[8]}

    out_path = f"{OUT}/labeled-catalog.sqlite"
    if os.path.exists(out_path):
        os.remove(out_path)
    odb = sqlite3.connect(out_path)
    odb.executescript(LABELED_CATALOG_SCHEMA)

    print(f"fetching printed_total for {len(sets)} sets + text for {len(card_ids)} cards from tcgdex...")
    for i, (set_id, s) in enumerate(sets.items()):
        printed = set_printed_total(set_id)
        odb.execute("INSERT INTO set_info VALUES (?,?,?,?,?,?,?)",
                    (s["id"], s["name"], s["release_date"], s["total"], printed, s["era"], None))
        print(f"  set {i+1}/{len(sets)}: {set_id} total={s['total']} printed_total={printed}")

    for i, cid in enumerate(card_ids):
        _, set_id, number, name, hp, *_ = rows[cid]
        body = card_text_body(cid)
        odb.execute("INSERT INTO card VALUES (?,?,?,?,?,?,?,?,?,?,?)",
                    (cid, set_id, number, name, hp, "", None, None, None, None, None))
        odb.execute("INSERT INTO card_text (card_id, name, body) VALUES (?,?,?)", (cid, name, body))
        if (i + 1) % 10 == 0:
            print(f"  card text {i+1}/{len(card_ids)}")

    for a, b in TWIN_PAIRS:
        if a in rows and b in rows:
            odb.execute("INSERT OR IGNORE INTO card_twin VALUES (?,?)", (a, b))
            odb.execute("INSERT OR IGNORE INTO card_twin VALUES (?,?)", (b, a))

    odb.commit()
    odb.close()
    print(f"wrote {out_path}")


def build_fingerprint_pack(truth_ids, distractor_ids):
    cb = cbmod.Codebook.load("fpcore/codebook.bin")
    out_path = f"{OUT}/labeled-pack.sqlite"
    if os.path.exists(out_path):
        os.remove(out_path)
    conn = fpdb.open_db(out_path)
    fpdb.write_meta(conn, cb.sha256_hex(), "2026-07-11T00:00:00Z")
    for cid in truth_ids + distractor_ids:
        p = f"{CACHE}/{cid}.webp"
        if not os.path.exists(p):
            print(f"  WARNING: {cid} missing from image cache, skipped")
            continue
        gray = canonicalize.canonicalize(cv2.imread(p))
        kps, desc = fpdesc.extract(gray)
        gvec = cb.global_vec(desc)
        import numpy as np
        xy = np.array([[k.x, k.y] for k in kps], dtype=np.float32) if len(kps) else np.zeros((0, 2), np.float32)
        fpdb.write_card_fp(conn, cid, packing.pack_global_vec(gvec), len(kps),
                            packing.pack_keypoints(xy), packing.pack_descriptors(desc))
    print(f"wrote {out_path} ({len(truth_ids) + len(distractor_ids)} cards, nf={fpdesc._orb().getMaxFeatures()})")


def main():
    os.makedirs(OUT, exist_ok=True)
    labels = build_labels()
    json.dump(labels, open(f"{OUT}/labels.json", "w"), indent=2)
    print(f"wrote {OUT}/labels.json ({len(labels)} photos)")

    truth_ids = sorted({cid for lab in labels for cid in lab["truthIds"]})
    print(f"{len(truth_ids)} unique truth card ids")

    cached_ids = [f[:-5] for f in os.listdir(CACHE) if f.endswith(".webp")]
    random.seed(11)
    distractor_ids = [c for c in random.sample(cached_ids, 3000) if c not in truth_ids][:N_DISTRACTORS]
    print(f"{len(distractor_ids)} distractor card ids")

    build_fingerprint_pack(truth_ids, distractor_ids)
    build_catalog_fixture(truth_ids + distractor_ids)


if __name__ == "__main__":
    main()
